In [1]:
import numpy as np
import pandas as pd

In [2]:
of = pd.read_excel("offtake with TP.xlsx", sheet_name='offt')

In [3]:
tp = pd.read_excel("offtake with TP.xlsx", sheet_name='tp')

In [4]:
of.head()

,Offtake Sales Value,Offtake Sales Qty,Date,Chain_Item_Code_External,Chain_Store_Code,CP Offer,CP Offer_in_Values,Offtake Sales in lakhs,Item Master.Item Description Internal,Brand,...,Variant,Item Master.Units,Offtake Sales Caselot,Item_Description_External,Store Master.Actual Store Count,Chain,Primary_Offtake Sales value,Primary_Offtake Sales value in lakhs,Merged,Primary grouped.AvgPrice
0,190,1,2019-01-01,Spencers_1309779,Spencers_H051,NaN,NaN,0.0019,Spinz Deo 150 ML Explorer,Spinz,...,Explorer,24,0.041667,SPINZ EXPLORER DEO 150ml,1,Spencers,NaN,NaN,Spencers;01-01-2019;Spinz Deo 150 ML Explorer,NaN
1,190,1,2019-01-01,Spencers_1309779,Spencers_H079,NaN,NaN,0.0019,Spinz Deo 150 ML Explorer,Spinz,...,Explorer,24,0.041667,SPINZ EXPLORER DEO 150ml,1,Spencers,NaN,NaN,Spencers;01-01-2019;Spinz Deo 150 ML Explorer,NaN
2,190,1,2019-01-01,Spencers_1309779,Spencers_H072,NaN,NaN,0.0019,Spinz Deo 150 ML Explorer,Spinz,...,Explorer,24,0.041667,SPINZ EXPLORER DEO 150ml,1,Spencers,NaN,NaN,Spencers;01-01-2019;Spinz Deo 150 ML Explorer,NaN
3,190,1,2019-10-01,Spencers_1309778,Spencers_H015,NaN,NaN,0.0019,Spinz Deo 150 ML Trailblazer,Spinz,...,Trailblazer,24,0.041667,SPINZ TRAIL BLAZER DEO 150ml,1,Spencers,NaN,NaN,Spencers;01-10-2019;Spinz Deo 150 ML Trailblazer,NaN
4,190,1,2019-10-01,Spencers_1309778,Spencers_H021,NaN,NaN,0.0019,Spinz Deo 150 ML Trailblazer,Spinz,...,Trailblazer,24,0.041667,SPINZ TRAIL BLAZER DEO 150ml,1,Spencers,NaN,NaN,Spencers;01-10-2019;Spinz Deo 150 ML Trailblazer,NaN

In [5]:
of.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134779 entries, 0 to 134778
Data columns (total 21 columns):
Offtake Sales Value                      134779 non-null int64
Offtake Sales Qty                        134779 non-null int64
Date                                     134779 non-null datetime64[ns]
Chain_Item_Code_External                 134779 non-null object
Chain_Store_Code                         134779 non-null object
CP Offer                                 36735 non-null object
CP Offer_in_Values                       36735 non-null float64
Offtake Sales in lakhs                   134779 non-null float64
Item Master.Item Description Internal    134779 non-null object
Brand                                    134779 non-null object
Category Internal                        134779 non-null object
Variant                                  134779 non-null object
Item Master.Units                        134779 non-null int64
Offtake Sales Caselot                    134779 non-null float64
Item_Description_External                134779 non-null object
Store Master.Actual Store Count          134779 non-null int64
Chain                                    134779 non-null object
Primary_Offtake Sales value              91671 non-null float64
Primary_Offtake Sales value in lakhs     91671 non-null float64
Merged                                   134779 non-null object
Primary grouped.AvgPrice                 91671 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(4), object(10)
memory usage: 21.6+ MB

In [6]:
tp.head()

,Month,Proper Chain Name,Store Code,Short Text,Gross Price,Element Type,Brand TP,Brand,Category,Variant
0,2019-04-01,Metro C&C,Metro C&C_10,END CAP 1-3-2019 TO 31-3-2019,50000.0,END CAP,SPINZ TALC,Spinz,Talc,All
1,2019-04-01,Metro C&C,Metro C&C_11,END CAP 1-3-2019 TO 31-3-2019,50000.0,END CAP,SPINZ TALC,Spinz,Talc,All
2,2019-04-01,Metro C&C,Metro C&C_12,END CAP 1-3-2019 TO 31-3-2019,50000.0,END CAP,SPINZ TALC,Spinz,Talc,All
3,2019-04-01,Metro C&C,Metro C&C_15,END CAP 1-3-2019 TO 31-3-2019,50000.0,END CAP,SPINZ TALC,Spinz,Talc,All
4,2019-04-01,Metro C&C,Metro C&C_20,END CAP 1-4-2019 TO 31-4-2019,50000.0,END CAP,INDICA EASY,Indica,Hair Colour,Easy

In [7]:
tp.columns

Index(['Month', 'Proper Chain Name', 'Store Code', 'Short Text', 'Gross Price',
       'Element Type', 'Brand TP', 'Brand', 'Category', 'Variant'],
      dtype='object')

In [8]:
tp.Category.unique()

array(['Talc', 'Hair Colour', 'Shampoo', 'Deo', 'Fairness Cream', 'All',
       'Men Deo', 'Lotion', 'Hair Wash Powder', 'BB'], dtype=object)

In [9]:
tp.loc[:,['Month', 'Brand']]

          Month   Brand
0    2019-04-01   Spinz
1    2019-04-01   Spinz
2    2019-04-01   Spinz
3    2019-04-01   Spinz
4    2019-04-01  Indica
...         ...     ...
1382 2020-02-01   Spinz
1383 2020-02-01   Spinz
1384 2020-02-01   Spinz
1385 2020-02-01   Spinz
1386 2020-02-01   Spinz

[1387 rows x 2 columns]

In [10]:
tp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1387 entries, 0 to 1386
Data columns (total 10 columns):
Month                1387 non-null datetime64[ns]
Proper Chain Name    1387 non-null object
Store Code           1387 non-null object
Short Text           1387 non-null object
Gross Price          1387 non-null float64
Element Type         1387 non-null object
Brand TP             1387 non-null object
Brand                1387 non-null object
Category             1387 non-null object
Variant              1387 non-null object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 108.5+ KB

In [11]:
tp.columns

Index(['Month', 'Proper Chain Name', 'Store Code', 'Short Text', 'Gross Price',
       'Element Type', 'Brand TP', 'Brand', 'Category', 'Variant'],
      dtype='object')

In [12]:
tp.loc[:,['Month', 'Proper Chain Name', 'Store Code', 'Brand', 'Category', 'Variant','Gross Price','Element Type']]

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
0,2019-04-01,Metro C&C,Metro C&C_10,Spinz,Talc,All,50000.0,END CAP
1,2019-04-01,Metro C&C,Metro C&C_11,Spinz,Talc,All,50000.0,END CAP
2,2019-04-01,Metro C&C,Metro C&C_12,Spinz,Talc,All,50000.0,END CAP
3,2019-04-01,Metro C&C,Metro C&C_15,Spinz,Talc,All,50000.0,END CAP
4,2019-04-01,Metro C&C,Metro C&C_20,Indica,Hair Colour,Easy,50000.0,END CAP
...,...,...,...,...,...,...,...,...
1382,2020-02-01,Tesco,Tesco_SM11,Spinz,Deo,All,40000.0,END CAP
1383,2020-02-01,Tesco,Tesco_SM39,Spinz,Deo,All,40000.0,END CAP
1384,2020-02-01,Tesco,Tesco_ST02,Spinz,Deo,All,40000.0,END CAP
1385,2020-02-01,Tesco,Tesco_ST05,Spinz,Deo,All,40000.0,END CAP
1386,2020-02-01,Tesco,Tesco_ST17,Spinz,Deo,All,40000.0,END CAP

In [13]:
tp_grouped = tp.loc[:,['Month', 'Proper Chain Name', 'Store Code', 'Brand', 'Category', 'Variant',
                       'Gross Price',
       'Element Type']].groupby(['Month', 'Proper Chain Name', 'Store Code', 'Brand', 'Category', 'Variant'])

new = tp.loc[:,['Month', 'Proper Chain Name', 'Store Code', 'Brand', 'Category', 'Variant','Element Type']].apply(lambda s: " ".join([str(i) for i in s]), axis=1)

len(new.unique())

In [14]:
tp_grouped = tp_grouped.aggregate({'Gross Price': 'sum', 'Element Type':lambda x:", ".join(i for i in x.value_counts().index)}).reset_index()

In [15]:
"||".join(i for i in tp_grouped['Element Type'].value_counts().index)

'END CAP||SIDE CAP||PARASITE||Floor Stack||SHELF VISIBILITY||FSU||End Cap||SIDE CAP, End Cap||END CAP, Floor Stack||SIDE CAP, PARASITE||PARASITE, SIDE CAP||Floor Stack, END CAP||End Cap, SIDE CAP||Floor Stack, SIDE CAP||SIDE CAP, END CAP||SIDE CAP, Floor Stack||END CAP, SIDE CAP||SHELF VISIBILITY, END CAP'

In [16]:
tp_grouped[(tp_grouped['Month']=='2019-05-01') & (tp_grouped['Store Code']=='ABRL_Super_Bangalore')]

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
69,2019-05-01,ABRL,ABRL_Super_Bangalore,Fairever,Fairness Cream,Next,438720.0,"PARASITE, SIDE CAP"
70,2019-05-01,ABRL,ABRL_Super_Bangalore,Spinz,Deo,All,161000.0,END CAP

In [17]:
tp_grouped['Element Type'].unique()

array(['END CAP', 'Floor Stack', 'PARASITE', 'SIDE CAP',
       'PARASITE, SIDE CAP', 'Floor Stack, END CAP', 'SIDE CAP, End Cap',
       'END CAP, SIDE CAP', 'END CAP, Floor Stack', 'SIDE CAP, PARASITE',
       'SIDE CAP, END CAP', 'FSU', 'SHELF VISIBILITY, END CAP',
       'SHELF VISIBILITY', 'End Cap', 'SIDE CAP, Floor Stack',
       'End Cap, SIDE CAP', 'Floor Stack, SIDE CAP'], dtype=object)

In [18]:
tp_grouped.sample(4)

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
100,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,Fairever,Fairness Cream,Next,35400.0,PARASITE
516,2019-10-01,ABRL,ABRL_Super_Kolkata,Indica,Hair Colour,Easy,145000.0,PARASITE
169,2019-07-01,Metro C&C,Metro C&C_12,Indica,Hair Colour,Creme,50000.0,END CAP
64,2019-04-01,Spencers,Spencers_H072,Spinz,Deo,All,110500.0,END CAP

In [19]:
tp['Gross Price'].sum()

39474929.0

In [20]:
tp_grouped['Gross Price'].sum()

39474929.0

In [21]:
of.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134779 entries, 0 to 134778
Data columns (total 21 columns):
Offtake Sales Value                      134779 non-null int64
Offtake Sales Qty                        134779 non-null int64
Date                                     134779 non-null datetime64[ns]
Chain_Item_Code_External                 134779 non-null object
Chain_Store_Code                         134779 non-null object
CP Offer                                 36735 non-null object
CP Offer_in_Values                       36735 non-null float64
Offtake Sales in lakhs                   134779 non-null float64
Item Master.Item Description Internal    134779 non-null object
Brand                                    134779 non-null object
Category Internal                        134779 non-null object
Variant                                  134779 non-null object
Item Master.Units                        134779 non-null int64
Offtake Sales Caselot                    134779 non-null float64
Item_Description_External                134779 non-null object
Store Master.Actual Store Count          134779 non-null int64
Chain                                    134779 non-null object
Primary_Offtake Sales value              91671 non-null float64
Primary_Offtake Sales value in lakhs     91671 non-null float64
Merged                                   134779 non-null object
Primary grouped.AvgPrice                 91671 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(4), object(10)
memory usage: 21.6+ MB

In [22]:
of.columns

Index(['Offtake Sales Value', 'Offtake Sales Qty', 'Date',
       'Chain_Item_Code_External', 'Chain_Store_Code', 'CP Offer',
       'CP Offer_in_Values', 'Offtake Sales in lakhs',
       'Item Master.Item Description Internal', 'Brand', 'Category Internal',
       'Variant', 'Item Master.Units', 'Offtake Sales Caselot',
       'Item_Description_External', 'Store Master.Actual Store Count', 'Chain',
       'Primary_Offtake Sales value', 'Primary_Offtake Sales value in lakhs',
       'Merged', 'Primary grouped.AvgPrice'],
      dtype='object')

In [23]:
of.sample(5)

,Offtake Sales Value,Offtake Sales Qty,Date,Chain_Item_Code_External,Chain_Store_Code,CP Offer,CP Offer_in_Values,Offtake Sales in lakhs,Item Master.Item Description Internal,Brand,...,Variant,Item Master.Units,Offtake Sales Caselot,Item_Description_External,Store Master.Actual Store Count,Chain,Primary_Offtake Sales value,Primary_Offtake Sales value in lakhs,Merged,Primary grouped.AvgPrice
17438,2494,893,2019-02-01,Reliance C&C_491046256,Reliance C&C_3264,NaN,NaN,0.02494,Meera S&H Rs 3 Sachet,Meera,...,Strong & Healthy,1350,0.661481,Meera Strong & helthy shampoo 7ml,1,Reliance C&C,NaN,NaN,Reliance C&C;01-02-2019;Meera S&H Rs 3 Sachet,NaN
86879,380,1,2019-03-01,Spencers_1296242,Spencers_D374,NaN,NaN,0.00380,Spinz Deo 150 ML 2+1,Spinz,...,2+1,8,0.125000,SPINZ DEO SPRAY 2+1 150ml,1,Spencers,255.66,0.0,Spencers;01-03-2019;Spinz Deo 150 ML 2+1,255.66
3753,68,1,2019-04-01,Metro C&C_378219,Metro C&C_27,NaN,NaN,0.00068,Indica Easy Pack of 2,Indica,...,Easy,36,0.027778,INDICA EASY PK OF 2- BLACK,1,Metro C&C,NaN,NaN,Metro C&C;01-04-2019;Indica Easy Pack of 2,NaN
131789,775,3,2019-04-01,Spar_114472006,Spar_30001,135,135.0,0.00775,Meera S&H 650 ML Bottle,Meera,...,Strong & Healthy,12,0.250000,MEERA SHAMPOO STRONG AND HEALTHY 650ML,1,Spar,NaN,NaN,Spar;01-04-2019;Meera S&H 650 ML Bottle,NaN
132038,3269,11,2019-03-01,Big Bazaar_1000697811,Big Bazaar_2579,135,135.0,0.03269,Meera S&H 650 ML Bottle,Meera,...,Strong & Healthy,12,0.916667,MEERA SHMP STRONG&HEALTHY BT 650ml,1,Big Bazaar,NaN,NaN,Big Bazaar;01-03-2019;Meera S&H 650 ML Bottle,NaN

In [24]:
of.columns

Index(['Offtake Sales Value', 'Offtake Sales Qty', 'Date',
       'Chain_Item_Code_External', 'Chain_Store_Code', 'CP Offer',
       'CP Offer_in_Values', 'Offtake Sales in lakhs',
       'Item Master.Item Description Internal', 'Brand', 'Category Internal',
       'Variant', 'Item Master.Units', 'Offtake Sales Caselot',
       'Item_Description_External', 'Store Master.Actual Store Count', 'Chain',
       'Primary_Offtake Sales value', 'Primary_Offtake Sales value in lakhs',
       'Merged', 'Primary grouped.AvgPrice'],
      dtype='object')

In [25]:
of2 = of.iloc[:, [0,1,2,3,4,8,9,10,11,12,13,14]]

In [26]:
of2.sample(3)

,Offtake Sales Value,Offtake Sales Qty,Date,Chain_Item_Code_External,Chain_Store_Code,Item Master.Item Description Internal,Brand,Category Internal,Variant,Item Master.Units,Offtake Sales Caselot,Item_Description_External
77264,3890,47,2019-12-01,Walmart_34373,Walmart_4760,Spinz Deo 150 ML Exotic,Spinz,Deo,Exotic,24,1.958333,SPINZ DEODORANT EXOTIC 150ml
93234,520,13,2019-03-01,Reliance Retail_491251629,Reliance Retail_Telangana,Indica Easy 25 ML Dark Brown,Indica,Hair Colour,Easy,72,0.180556,INDICA EASY HAIR CLR DARK BROWN 25 ml PP
128384,250,1,2019-05-01,Big Bazaar_1000892074,Big Bazaar_2512,Nyle AD 800 ML,Nyle,Shampoo,AD,12,0.083333,NYLE SHMP ANTI DANDRUFF BT 800ml

In [27]:
of2.iloc[:,[2,4,6,7,8]].columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant'], dtype='object')

In [28]:
of2.columns

Index(['Offtake Sales Value', 'Offtake Sales Qty', 'Date',
       'Chain_Item_Code_External', 'Chain_Store_Code',
       'Item Master.Item Description Internal', 'Brand', 'Category Internal',
       'Variant', 'Item Master.Units', 'Offtake Sales Caselot',
       'Item_Description_External'],
      dtype='object')

In [29]:
of2_grouped = of2.groupby(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant']).aggregate({
    'Offtake Sales Value':'sum', 'Offtake Sales Qty':'sum', 
    'Item Master.Item Description Internal': lambda s: len(s.unique()),
    'Item_Description_External': lambda s: s.unique()[0]
})

In [30]:
of2_grouped.sort_values('Item Master.Item Description Internal', ascending=False).head(10)

,,,,,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External
Date,Chain_Store_Code,Brand,Category Internal,Variant,,,,
2019-11-01,Metro C&C_15,Indica,Hair Colour,Creme,33505,1765,7,INDICA 10MINS CREME HC ETU-BURG
2019-06-01,Metro C&C_15,Meera,Shampoo,Strong & Healthy,276156,3256,7,MEERA STRONG&HEALTHY SH 7ML PK80
2019-11-01,Reliance C&C_3238,Meera,Shampoo,Strong & Healthy,12319,1208,7,Meera Strong & helthy shampoo 7ml
2019-08-01,Metro C&C_17,Meera,Shampoo,Strong & Healthy,1197400,17652,7,MEERA STRONG&HEALTHY SH6ML PK60
2019-09-01,Metro C&C_17,Indica,Hair Colour,Creme,21478,1135,7,INDICA CERME HC NATURALBLCK80M
2019-07-01,Reliance C&C_3124,Meera,Shampoo,Strong & Healthy,745714,100283,7,Meera Strong & helthy shampoo 7ml
2019-09-01,Reliance C&C_3235,Meera,Shampoo,Strong & Healthy,59594,19944,7,Meera Strong & helthy shampoo 7ml
2019-06-01,Reliance C&C_3224,Meera,Shampoo,Strong & Healthy,17093,6314,7,Meera Strong & helthy shampoo 7ml
2020-01-01,Metro C&C_28,Indica,Hair Colour,Creme,11553,586,7,INDICA 10MINS CREME HC ETU-BURG
2019-11-01,Reliance C&C_3243,Meera,Shampoo,Strong & Healthy,14267,6315,7,Meera Strong & helthy shampoo 7ml

In [31]:
of2_grouped = of2_grouped.reset_index()

In [32]:
of2_grouped

,Date,Chain_Store_Code,Brand,Category Internal,Variant,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,3405,30,2,Chik Egg White Protein Shampoo180 ml Bottle
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,559,12,1,Fairever Fairness Cream 25 Gm
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,5254,29,3,IndicaBeard and Moustache Natural Black 32 gm Box
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,7975,210,3,Indica Easy Hair Color Natural Black25 ml Pouch
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,370,5,1,Karthika Shampoo Dryness Shield 175 Ml Bottle
...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,0,0,1,INDICA HAIR COLOR NATURAL BLACK 40 ml
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,232,2,1,INDICA HAIR COLOUR NAT BLK 8UX5g
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,841,31,1,INDICA HAIR COLOR NATURAL BLACK 25 ml
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,0,0,1,KARTHIKA SHAMPOO 20U X 6ml
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,329949,11919,1,MEERA SHAMPOO STRNGHLTHY 20 U X 6 ml

In [33]:
tp_grouped

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
0,2019-04-01,Metro C&C,Metro C&C_10,Spinz,Talc,All,50000.0,END CAP
1,2019-04-01,Metro C&C,Metro C&C_11,Spinz,Talc,All,50000.0,END CAP
2,2019-04-01,Metro C&C,Metro C&C_12,Spinz,Talc,All,50000.0,END CAP
3,2019-04-01,Metro C&C,Metro C&C_15,Spinz,Talc,All,50000.0,END CAP
4,2019-04-01,Metro C&C,Metro C&C_20,Indica,Hair Colour,Easy,50000.0,END CAP
...,...,...,...,...,...,...,...,...
816,2020-02-01,Tesco,Tesco_SM11,Spinz,Deo,All,40000.0,END CAP
817,2020-02-01,Tesco,Tesco_SM39,Spinz,Deo,All,40000.0,END CAP
818,2020-02-01,Tesco,Tesco_ST02,Spinz,Deo,All,40000.0,END CAP
819,2020-02-01,Tesco,Tesco_ST05,Spinz,Deo,All,40000.0,END CAP
820,2020-02-01,Tesco,Tesco_ST17,Spinz,Deo,All,40000.0,END CAP

In [34]:
of2_grouped.columns, tp_grouped.columns

(Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant',
        'Offtake Sales Value', 'Offtake Sales Qty',
        'Item Master.Item Description Internal', 'Item_Description_External'],
       dtype='object'),
 Index(['Month', 'Proper Chain Name', 'Store Code', 'Brand', 'Category',
        'Variant', 'Gross Price', 'Element Type'],
       dtype='object'))

In [35]:
of = of2_grouped.copy()
tp = tp_grouped.copy()

In [36]:
del of2, of2_grouped, tp_grouped

Start with dividing the tp data:

In [37]:
tp.sample()

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
645,2019-10-01,Spencers,Spencers_S038,Nyle,Shampoo,All,9555.0,END CAP

In [38]:
tp1  = tp[(tp.Category=='All') & (tp.Variant=='All')]

In [39]:
tp2  = tp[(tp.Category!='All') & (tp.Variant=='All')]

In [40]:
tp3 = tp[(tp.Category!='All') & (tp.Variant!='All')]

In [41]:
tp.index

RangeIndex(start=0, stop=821, step=1)

In [42]:
type(tp.index)

pandas.core.indexes.range.RangeIndex

Make m1 dat from tp1 and of

In [43]:
tp1.sample()

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
101,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,Spinz,All,All,92925.0,SIDE CAP

In [44]:
of.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External
76834,2019-11-01,Walmart_4813,Indica,Hair Colour,Dye,12323,113,1,INDICA HAIR COLOUR NAT BLK 8UX5g

In [45]:
m1 = pd.merge(left=of, right=tp1, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand'],
        right_on=['Month', 'Store Code', 'Brand'])

In [46]:
m1

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Month,Proper Chain Name,Store Code,Category,Variant_y,Gross Price,Element Type
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,3405,30,2,Chik Egg White Protein Shampoo180 ml Bottle,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,559,12,1,Fairever Fairness Cream 25 Gm,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,5254,29,3,IndicaBeard and Moustache Natural Black 32 gm Box,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,7975,210,3,Indica Easy Hair Color Natural Black25 ml Pouch,NaT,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,370,5,1,Karthika Shampoo Dryness Shield 175 Ml Bottle,NaT,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,0,0,1,INDICA HAIR COLOR NATURAL BLACK 40 ml,NaT,NaN,NaN,NaN,NaN,NaN,NaN
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,232,2,1,INDICA HAIR COLOUR NAT BLK 8UX5g,NaT,NaN,NaN,NaN,NaN,NaN,NaN
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,841,31,1,INDICA HAIR COLOR NATURAL BLACK 25 ml,NaT,NaN,NaN,NaN,NaN,NaN,NaN
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,0,0,1,KARTHIKA SHAMPOO 20U X 6ml,NaT,NaN,NaN,NaN,NaN,NaN,NaN
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,329949,11919,1,MEERA SHAMPOO STRNGHLTHY 20 U X 6 ml,NaT,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
m1[~m1['Month'].isna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Month,Proper Chain Name,Store Code,Category,Variant_y,Gross Price,Element Type
30759,2019-05-01,Reliance Retail_Jharkhand,Spinz,DEO,Enchante,18230,96,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30760,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Exotic,11780,62,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30761,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Livewire,8143,51,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30762,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Pack of 2,1500,5,1,SPINZ PERFUMED DEO PACK OF 2 CAN,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30763,2019-05-01,Reliance Retail_Jharkhand,Spinz,Men Deo,Hi Flyer,5836,43,1,SPINZ DEO HI FLYER 150 ML,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30764,2019-05-01,Reliance Retail_Jharkhand,Spinz,Talc,Enchante,2640,15,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,All,All,61950.0,SIDE CAP
30779,2019-05-01,Reliance Retail_Karnataka,Spinz,BB,Cream,5130,54,1,SPINZ BB CREAM 29 g TUB,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30780,2019-05-01,Reliance Retail_Karnataka,Spinz,BB,Talc,6659,83,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30781,2019-05-01,Reliance Retail_Karnataka,Spinz,DEO,Enchante,15570,82,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30782,2019-05-01,Reliance Retail_Karnataka,Spinz,Deo,Exotic,12920,68,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30783,2019-05-01,Reliance Retail_Karnataka,Spinz,Deo,Livewire,8730,46,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30784,2019-05-01,Reliance Retail_Karnataka,Spinz,Men Deo,Hi Flyer,940,5,1,SPINZ DEO HI FLYER 150 ML,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30785,2019-05-01,Reliance Retail_Karnataka,Spinz,Talc,Enchante,1520,8,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,All,All,92925.0,SIDE CAP
30810,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,BB,Cream,1805,19,1,SPINZ BB CREAM 29 g TUB,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30811,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,BB,Talc,4557,55,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30812,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,DEO,Enchante,2470,13,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30813,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,2+1,1140,3,1,SPINZ DEO 150 ml 2+1 CAN,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30814,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,Exotic,2250,12,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30815,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,Livewire,1490,8,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30816,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Talc,Enchante,350,2,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,All,All,30975.0,SIDE CAP
30826,2019-05-01,Reliance Retail_Maharashtra,Spinz,BB,Cream,3164,34,1,SPINZ BB CREAM 29 g TUB,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30827,2019-05-01,Reliance Retail_Maharashtra,Spinz,BB,Talc,1494,18,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30828,2019-05-01,Reliance Retail_Maharashtra,Spinz,DEO,Enchante,17650,105,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30829,2019-05-01,Reliance Retail_Maharashtra,Spinz,Deo,Exotic,12589,70,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30830,2019-05-01,Reliance Retail_Maharashtra,Spinz,Deo,Livewire,5599,31,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30831,2019-05-01,Reliance Retail_Maharashtra,Spinz,Men Deo,Hi Flyer,2260,12,1,SPINZ DEO HI FLYER 150 ML,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30832,2019-05-01,Reliance Retail_Maharashtra,Spinz,Talc,Enchante,1850,11,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,All,All,30975.0,SIDE CAP
30857,2019-05-01,Reliance Retail_NCR,Spinz,BB,Talc,6225,75,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,2019-05-01,Reliance Retail,Reliance Retail_NCR,All,All,154875.0,SIDE CAP
30858,2019-05-01,Reliance Retail_NCR,Spinz,DEO,Enchante,13486,73,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_NCR,All,All,154875.0,SIDE CAP
30859,2019-05-01,Reliance Retail_NCR,Spinz,Deo,Exotic,10680,59,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_NCR,All,All,154875.0,SIDE CAP
30860,2019-05-01,Reliance Retail_NCR,Spinz,Deo,Livewire,750,4,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_NCR,All,All,154875.0,SIDE CAP
30861,2019-05-01,Reliance Retail_NCR,Spinz,Talc,Enchante,1225,7,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_NCR,All,All,154875.0,SIDE CAP
30928,2019-05-01,Reliance Retail_Telangana,Spinz,BB,Cream,12713,179,2,SPINZ BB CREAM 29 g TUB,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30929,2019-05-01,Reliance Retail_Telangana,Spinz,BB,Talc,2482,30,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30930,2019-05-01,Reliance Retail_Telangana,Spinz,DEO,Enchante,17651,94,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30931,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Achiever,-150,-1,1,SPINZ ACHIEVER PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30932,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Exotic,17075,91,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30933,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Livewire,6980,37,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30934,2019-05-01,Reliance Retail_Telangana,Spinz,Men Deo,Hi Flyer,1820,10,1,SPINZ DEO HI FLYER 150 ML,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30935,2019-05-01,Reliance Retail_Telangana,Spinz,Talc,Enchante,8925,51,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_Telangana,All,All,30975.0,SIDE CAP
30943,2019-05-01,Reliance Retail_West Bengal,Spinz,DEO,Enchante,6840,36,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,All,All,30975.0,SIDE CAP
30944,2019-05-01,Reliance Retail_West Bengal,Spinz,Deo,Exotic,5510,29,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,All,All,30975.0,SIDE CAP
30945,2019-05-01,Reliance Retail_West Bengal,Spinz,Deo,Livewire,4370,23,1,SPINZ DEO LIVEWIRE 150 ml CAN,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,All,All,30975.0,SIDE CAP
30946,2019-05-01,Reliance Retail_West Bengal,Spinz,Men Deo,Hi Flyer,6080,32,1,SPINZ DEO HI FLYER 150 ML,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,All,All,30975.0,SIDE CAP
30947,2019-05-01,Reliance Retail_West Bengal,Spinz,Talc,Enchante,1425,8,1,SPINZ ENCHANTE TALC 400 g BTL,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,All,All,30975.0,SIDE CAP

In [48]:
m1 = m1[['Date', 'Chain_Store_Code', 'Brand',
          'Category Internal', 'Variant_x', 
          'Offtake Sales Value','Offtake Sales Qty','Item Master.Item Description Internal',
          'Item_Description_External', 'Gross Price', 'Element Type']]

In [49]:
m1.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal', 'Item_Description_External',
       'Gross Price', 'Element Type'],
      dtype='object')

In [50]:
m1.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type
78010,2019-12-01,Metro C&C_16,Spinz,Deo,Trailblazer,3876,29,1,SPINZ DEO TRAIL BLAZER 150ML,NaN,NaN

In [51]:
m1[~m1['Gross Price'].isna()].sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type
30813,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,2+1,1140,3,1,SPINZ DEO 150 ml 2+1 CAN,30975.0,SIDE CAP

In [52]:
m12 = m1.groupby(['Date', 'Chain_Store_Code', 'Brand']).aggregate({'Gross Price': lambda s: s.mean(), 
                                                'Item_Description_External':lambda s: s.count(),
                                                                  'Element Type': lambda s: s.unique()}).reset_index()

In [53]:
tp1

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
99,2019-05-01,Reliance Retail,Reliance Retail_Jharkhand,Spinz,All,All,61950.0,SIDE CAP
101,2019-05-01,Reliance Retail,Reliance Retail_Karnataka,Spinz,All,All,92925.0,SIDE CAP
103,2019-05-01,Reliance Retail,Reliance Retail_Madhya Pradesh,Spinz,All,All,30975.0,SIDE CAP
105,2019-05-01,Reliance Retail,Reliance Retail_Maharashtra,Spinz,All,All,30975.0,SIDE CAP
106,2019-05-01,Reliance Retail,Reliance Retail_NCR,Spinz,All,All,154875.0,SIDE CAP
109,2019-05-01,Reliance Retail,Reliance Retail_Telangana,Spinz,All,All,30975.0,SIDE CAP
111,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,Spinz,All,All,30975.0,SIDE CAP

In [54]:
m12[m12['Gross Price'].notna()]

,Date,Chain_Store_Code,Brand,Gross Price,Item_Description_External,Element Type
8059,2019-05-01,Reliance Retail_Jharkhand,Spinz,61950.0,6,SIDE CAP
8065,2019-05-01,Reliance Retail_Karnataka,Spinz,92925.0,7,SIDE CAP
8075,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,30975.0,7,SIDE CAP
8080,2019-05-01,Reliance Retail_Maharashtra,Spinz,30975.0,7,SIDE CAP
8088,2019-05-01,Reliance Retail_NCR,Spinz,154875.0,5,SIDE CAP
8111,2019-05-01,Reliance Retail_Telangana,Spinz,30975.0,8,SIDE CAP
8116,2019-05-01,Reliance Retail_West Bengal,Spinz,30975.0,5,SIDE CAP

In [55]:
m12['Promotion1'] = m12.loc[:,'Gross Price']/m12.loc[:,'Item_Description_External']

In [56]:
m12 = m12[~m12['Gross Price'].isna()]

In [57]:
m12.drop(columns=['Gross Price', 'Item_Description_External'], inplace=True)

In [58]:
m12.sample()

           Date           Chain_Store_Code  Brand Element Type  Promotion1
8065 2019-05-01  Reliance Retail_Karnataka  Spinz     SIDE CAP     13275.0

In [59]:
m1.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type
85398,2020-01-01,Spencers_H042,Spinz,Deo,Trailblazer,380,3,1,SPINZ TRAIL BLAZER DEO 150ml,NaN,NaN

In [60]:
of_tp = pd.merge(left=m1, right=m12, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand'],
        right_on=['Date', 'Chain_Store_Code', 'Brand'])

In [61]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type_x,Element Type_y,Promotion1
33221,2019-05-01,Spencers_S068,Meera,Hair Wash Powder,Powder,63,1,1,MEERA HAIR WASH PWDR RFL 80g,NaN,NaN,NaN,NaN

In [62]:
temp = of_tp[~of_tp['Item_Description_External'].isna()]
temp

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type_x,Element Type_y,Promotion1
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,3405,30,2,Chik Egg White Protein Shampoo180 ml Bottle,NaN,NaN,NaN,NaN
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,559,12,1,Fairever Fairness Cream 25 Gm,NaN,NaN,NaN,NaN
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,5254,29,3,IndicaBeard and Moustache Natural Black 32 gm Box,NaN,NaN,NaN,NaN
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,7975,210,3,Indica Easy Hair Color Natural Black25 ml Pouch,NaN,NaN,NaN,NaN
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,370,5,1,Karthika Shampoo Dryness Shield 175 Ml Bottle,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,0,0,1,INDICA HAIR COLOR NATURAL BLACK 40 ml,NaN,NaN,NaN,NaN
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,232,2,1,INDICA HAIR COLOUR NAT BLK 8UX5g,NaN,NaN,NaN,NaN
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,841,31,1,INDICA HAIR COLOR NATURAL BLACK 25 ml,NaN,NaN,NaN,NaN
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,0,0,1,KARTHIKA SHAMPOO 20U X 6ml,NaN,NaN,NaN,NaN
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,329949,11919,1,MEERA SHAMPOO STRNGHLTHY 20 U X 6 ml,NaN,NaN,NaN,NaN

In [63]:
(of_tp['Element Type_x']==of_tp['Element Type_y']).sum()

45

In [64]:
tp1.sample()

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
111,2019-05-01,Reliance Retail,Reliance Retail_West Bengal,Spinz,All,All,30975.0,SIDE CAP

In [65]:
tp1['Gross Price'].sum()

433650.0

In [66]:
temp['Promotion1'].sum()

433650.0

In [67]:
of_tp.sample(3)

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type_x,Element Type_y,Promotion1
35872,2019-06-01,Big Bazaar_2588,Nyle,Shampoo,AD,620,2,1,NYLE SHMP ANTI DANDRUFF BT 800ml,NaN,NaN,NaN,NaN
25741,2019-04-01,Walmart_4724,Spinz,Deo,Pack of 6,0,0,1,Spinz Deo Pack of 6 50 ML,NaN,NaN,NaN,NaN
37825,2019-06-01,Big Bazaar_5547,Spinz,BB,Talc,603,9,1,SPINZ TALC BRIGHTENING & BEUTY BT 100g,NaN,NaN,NaN,NaN

In [68]:
of_tp[of_tp['Promotion1'].notna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Gross Price,Element Type_x,Element Type_y,Promotion1
30759,2019-05-01,Reliance Retail_Jharkhand,Spinz,DEO,Enchante,18230,96,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,61950.0,SIDE CAP,SIDE CAP,10325.000
30760,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Exotic,11780,62,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,61950.0,SIDE CAP,SIDE CAP,10325.000
30761,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Livewire,8143,51,1,SPINZ DEO LIVEWIRE 150 ml CAN,61950.0,SIDE CAP,SIDE CAP,10325.000
30762,2019-05-01,Reliance Retail_Jharkhand,Spinz,Deo,Pack of 2,1500,5,1,SPINZ PERFUMED DEO PACK OF 2 CAN,61950.0,SIDE CAP,SIDE CAP,10325.000
30763,2019-05-01,Reliance Retail_Jharkhand,Spinz,Men Deo,Hi Flyer,5836,43,1,SPINZ DEO HI FLYER 150 ML,61950.0,SIDE CAP,SIDE CAP,10325.000
30764,2019-05-01,Reliance Retail_Jharkhand,Spinz,Talc,Enchante,2640,15,1,SPINZ ENCHANTE TALC 400 g BTL,61950.0,SIDE CAP,SIDE CAP,10325.000
30779,2019-05-01,Reliance Retail_Karnataka,Spinz,BB,Cream,5130,54,1,SPINZ BB CREAM 29 g TUB,92925.0,SIDE CAP,SIDE CAP,13275.000
30780,2019-05-01,Reliance Retail_Karnataka,Spinz,BB,Talc,6659,83,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,92925.0,SIDE CAP,SIDE CAP,13275.000
30781,2019-05-01,Reliance Retail_Karnataka,Spinz,DEO,Enchante,15570,82,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,92925.0,SIDE CAP,SIDE CAP,13275.000
30782,2019-05-01,Reliance Retail_Karnataka,Spinz,Deo,Exotic,12920,68,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,92925.0,SIDE CAP,SIDE CAP,13275.000
30783,2019-05-01,Reliance Retail_Karnataka,Spinz,Deo,Livewire,8730,46,1,SPINZ DEO LIVEWIRE 150 ml CAN,92925.0,SIDE CAP,SIDE CAP,13275.000
30784,2019-05-01,Reliance Retail_Karnataka,Spinz,Men Deo,Hi Flyer,940,5,1,SPINZ DEO HI FLYER 150 ML,92925.0,SIDE CAP,SIDE CAP,13275.000
30785,2019-05-01,Reliance Retail_Karnataka,Spinz,Talc,Enchante,1520,8,1,SPINZ ENCHANTE TALC 400 g BTL,92925.0,SIDE CAP,SIDE CAP,13275.000
30810,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,BB,Cream,1805,19,1,SPINZ BB CREAM 29 g TUB,30975.0,SIDE CAP,SIDE CAP,4425.000
30811,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,BB,Talc,4557,55,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,30975.0,SIDE CAP,SIDE CAP,4425.000
30812,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,DEO,Enchante,2470,13,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30813,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,2+1,1140,3,1,SPINZ DEO 150 ml 2+1 CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30814,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,Exotic,2250,12,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30815,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Deo,Livewire,1490,8,1,SPINZ DEO LIVEWIRE 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30816,2019-05-01,Reliance Retail_Madhya Pradesh,Spinz,Talc,Enchante,350,2,1,SPINZ ENCHANTE TALC 400 g BTL,30975.0,SIDE CAP,SIDE CAP,4425.000
30826,2019-05-01,Reliance Retail_Maharashtra,Spinz,BB,Cream,3164,34,1,SPINZ BB CREAM 29 g TUB,30975.0,SIDE CAP,SIDE CAP,4425.000
30827,2019-05-01,Reliance Retail_Maharashtra,Spinz,BB,Talc,1494,18,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,30975.0,SIDE CAP,SIDE CAP,4425.000
30828,2019-05-01,Reliance Retail_Maharashtra,Spinz,DEO,Enchante,17650,105,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30829,2019-05-01,Reliance Retail_Maharashtra,Spinz,Deo,Exotic,12589,70,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30830,2019-05-01,Reliance Retail_Maharashtra,Spinz,Deo,Livewire,5599,31,1,SPINZ DEO LIVEWIRE 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,4425.000
30831,2019-05-01,Reliance Retail_Maharashtra,Spinz,Men Deo,Hi Flyer,2260,12,1,SPINZ DEO HI FLYER 150 ML,30975.0,SIDE CAP,SIDE CAP,4425.000
30832,2019-05-01,Reliance Retail_Maharashtra,Spinz,Talc,Enchante,1850,11,1,SPINZ ENCHANTE TALC 400 g BTL,30975.0,SIDE CAP,SIDE CAP,4425.000
30857,2019-05-01,Reliance Retail_NCR,Spinz,BB,Talc,6225,75,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,154875.0,SIDE CAP,SIDE CAP,30975.000
30858,2019-05-01,Reliance Retail_NCR,Spinz,DEO,Enchante,13486,73,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,154875.0,SIDE CAP,SIDE CAP,30975.000
30859,2019-05-01,Reliance Retail_NCR,Spinz,Deo,Exotic,10680,59,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,154875.0,SIDE CAP,SIDE CAP,30975.000
30860,2019-05-01,Reliance Retail_NCR,Spinz,Deo,Livewire,750,4,1,SPINZ DEO LIVEWIRE 150 ml CAN,154875.0,SIDE CAP,SIDE CAP,30975.000
30861,2019-05-01,Reliance Retail_NCR,Spinz,Talc,Enchante,1225,7,1,SPINZ ENCHANTE TALC 400 g BTL,154875.0,SIDE CAP,SIDE CAP,30975.000
30928,2019-05-01,Reliance Retail_Telangana,Spinz,BB,Cream,12713,179,2,SPINZ BB CREAM 29 g TUB,30975.0,SIDE CAP,SIDE CAP,3871.875
30929,2019-05-01,Reliance Retail_Telangana,Spinz,BB,Talc,2482,30,1,SPINZ BRIGHTENIG & BEAUTY TALC 80 g PET,30975.0,SIDE CAP,SIDE CAP,3871.875
30930,2019-05-01,Reliance Retail_Telangana,Spinz,DEO,Enchante,17651,94,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,3871.875
30931,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Achiever,-150,-1,1,SPINZ ACHIEVER PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,3871.875
30932,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Exotic,17075,91,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,3871.875
30933,2019-05-01,Reliance Retail_Telangana,Spinz,Deo,Livewire,6980,37,1,SPINZ DEO LIVEWIRE 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,3871.875
30934,2019-05-01,Reliance Retail_Telangana,Spinz,Men Deo,Hi Flyer,1820,10,1,SPINZ DEO HI FLYER 150 ML,30975.0,SIDE CAP,SIDE CAP,3871.875
30935,2019-05-01,Reliance Retail_Telangana,Spinz,Talc,Enchante,8925,51,1,SPINZ ENCHANTE TALC 400 g BTL,30975.0,SIDE CAP,SIDE CAP,3871.875
30943,2019-05-01,Reliance Retail_West Bengal,Spinz,DEO,Enchante,6840,36,1,SPINZ ENCHANTE PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,6195.000
30944,2019-05-01,Reliance Retail_West Bengal,Spinz,Deo,Exotic,5510,29,1,SPINZ EXOTIC PERFUMED DEO 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,6195.000
30945,2019-05-01,Reliance Retail_West Bengal,Spinz,Deo,Livewire,4370,23,1,SPINZ DEO LIVEWIRE 150 ml CAN,30975.0,SIDE CAP,SIDE CAP,6195.000
30946,2019-05-01,Reliance Retail_West Bengal,Spinz,Men Deo,Hi Flyer,6080,32,1,SPINZ DEO HI FLYER 150 ML,30975.0,SIDE CAP,SIDE CAP,6195.000
30947,2019-05-01,Reliance Retail_West Bengal,Spinz,Talc,Enchante,1425,8,1,SPINZ ENCHANTE TALC 400 g BTL,30975.0,SIDE CAP,SIDE CAP,6195.000

In [69]:
of_tp.drop(columns=['Gross Price', 'Element Type_y'], inplace=True)

In [70]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1
46204,2019-07-01,Big Bazaar_4987,Spinz,Deo,2+1,380,1,1,SPINZ DEO ASSORTED 2+1 150ml,NaN,NaN

In [71]:
of

,Date,Chain_Store_Code,Brand,Category Internal,Variant,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,3405,30,2,Chik Egg White Protein Shampoo180 ml Bottle
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,559,12,1,Fairever Fairness Cream 25 Gm
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,5254,29,3,IndicaBeard and Moustache Natural Black 32 gm Box
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,7975,210,3,Indica Easy Hair Color Natural Black25 ml Pouch
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,370,5,1,Karthika Shampoo Dryness Shield 175 Ml Bottle
...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,0,0,1,INDICA HAIR COLOR NATURAL BLACK 40 ml
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,232,2,1,INDICA HAIR COLOUR NAT BLK 8UX5g
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,841,31,1,INDICA HAIR COLOR NATURAL BLACK 25 ml
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,0,0,1,KARTHIKA SHAMPOO 20U X 6ml
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,329949,11919,1,MEERA SHAMPOO STRNGHLTHY 20 U X 6 ml

Make m2 from of_tp

In [72]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1
23823,2019-04-01,Spencers_H070,Spinz,BB,Cream,1135,9,2,SPINZ BB CREAM 29G,NaN,NaN

In [73]:
tp2.sample()

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
340,2019-08-01,Reliance C&C,Reliance C&C_3249,Spinz,Talc,All,50000.0,Floor Stack

In [74]:
m2 = pd.merge(left=of_tp, right=tp2, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal'],
        right_on=['Month', 'Store Code', 'Brand', 'Category'])

In [75]:
m2[~m2['Category'].isna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1,Month,Proper Chain Name,Store Code,Category,Variant,Gross Price,Element Type
20960,2019-04-01,Metro C&C_10,Spinz,Talc,Cool,2836,59,1,SPINZ COOL TALC 100G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20961,2019-04-01,Metro C&C_10,Spinz,Talc,Enchante,6328,125,1,SPINZ TALC ENCHANTE 100GM,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20962,2019-04-01,Metro C&C_10,Spinz,Talc,Exotic,6387,118,2,SPINZ TALC EXOTIC 100GM,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20963,2019-04-01,Metro C&C_10,Spinz,Talc,Sandal,3252,63,1,SPINZ SANDAL TALC 90G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20995,2019-04-01,Metro C&C_11,Spinz,Talc,Cool,6442,132,1,SPINZ COOL TALC 100G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_11,Talc,All,50000.0,END CAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82568,2020-01-01,ABRL_Super_Bangalore,Spinz,Men Deo,Risk Taker,14697,147,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Bangalore,Men Deo,All,285000.0,SIDE CAP
82698,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Flyer,10994,105,1,Spinz High Flyer 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82699,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Rider,12488,124,1,Spinz High Rider 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82700,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Master Mover,15291,151,1,Spinz Master Mover 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82701,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Risk Taker,15694,157,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP

In [76]:
m2.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1,Month,Proper Chain Name,Store Code,Category,Variant,Gross Price,Element Type
38120,2019-06-01,Metro C&C_18,Spinz,BB,Talc,5543,80,2,SPINZ BB TALC 15GM SET OF 12,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
m2[m2['Gross Price'].notna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1,Month,Proper Chain Name,Store Code,Category,Variant,Gross Price,Element Type
20960,2019-04-01,Metro C&C_10,Spinz,Talc,Cool,2836,59,1,SPINZ COOL TALC 100G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20961,2019-04-01,Metro C&C_10,Spinz,Talc,Enchante,6328,125,1,SPINZ TALC ENCHANTE 100GM,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20962,2019-04-01,Metro C&C_10,Spinz,Talc,Exotic,6387,118,2,SPINZ TALC EXOTIC 100GM,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20963,2019-04-01,Metro C&C_10,Spinz,Talc,Sandal,3252,63,1,SPINZ SANDAL TALC 90G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_10,Talc,All,50000.0,END CAP
20995,2019-04-01,Metro C&C_11,Spinz,Talc,Cool,6442,132,1,SPINZ COOL TALC 100G,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_11,Talc,All,50000.0,END CAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82568,2020-01-01,ABRL_Super_Bangalore,Spinz,Men Deo,Risk Taker,14697,147,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Bangalore,Men Deo,All,285000.0,SIDE CAP
82698,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Flyer,10994,105,1,Spinz High Flyer 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82699,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Rider,12488,124,1,Spinz High Rider 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82700,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Master Mover,15291,151,1,Spinz Master Mover 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP
82701,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Risk Taker,15694,157,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Hyderabad,Men Deo,All,47700.0,SIDE CAP

m2 = m2[['Date', 'Chain_Store_Code', 'Brand',
          'Category Internal', 'Variant_x', 
          'Offtake Sales Value','Offtake Sales Qty','Item Master.Item Description Internal',
         'Proper Chain Name_x','Gross Price_x','Element Type_x','Promotion1',
          'Proper Chain Name_y', 'Gross Price_y', 'Element Type']]

In [78]:
m2.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal', 'Item_Description_External',
       'Element Type_x', 'Promotion1', 'Month', 'Proper Chain Name',
       'Store Code', 'Category', 'Variant', 'Gross Price', 'Element Type'],
      dtype='object')

In [79]:
m2 = m2[['Date', 'Chain_Store_Code', 'Brand',
          'Category Internal', 'Variant_x', 
          'Offtake Sales Value','Offtake Sales Qty','Item Master.Item Description Internal',
         'Item_Description_External','Element Type_x','Promotion1',
           'Gross Price', 'Element Type']]

In [80]:
m22 = m2.groupby(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal']).aggregate({'Gross Price': lambda s: s.mean(), 
                                                'Item_Description_External':lambda s: s.count(),
                                                'Element Type': lambda s: s.unique()}).reset_index()

In [81]:
m22.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Gross Price,Item_Description_External,Element Type
15300,2019-05-01,Spencers_D019,Meera,Shampoo,NaN,3,NaN

In [82]:
m22['Promotion2'] = m22.loc[:,'Gross Price']/m22.loc[:,'Item_Description_External']

In [83]:
m22 = m22[~m22['Gross Price'].isna()]

In [84]:
m22

,Date,Chain_Store_Code,Brand,Category Internal,Gross Price,Item_Description_External,Element Type,Promotion2
10247,2019-04-01,Metro C&C_10,Spinz,Talc,50000.0,4,END CAP,12500.000000
10261,2019-04-01,Metro C&C_11,Spinz,Talc,50000.0,4,END CAP,12500.000000
10275,2019-04-01,Metro C&C_12,Spinz,Talc,50000.0,4,END CAP,12500.000000
10288,2019-04-01,Metro C&C_15,Spinz,Talc,50000.0,4,END CAP,12500.000000
10348,2019-04-01,Metro C&C_20,Spinz,Talc,50000.0,1,END CAP,50000.000000
...,...,...,...,...,...,...,...,...
37320,2019-12-01,Metro C&C_12,Spinz,Deo,50000.0,6,END CAP,8333.333333
37376,2019-12-01,Metro C&C_18,Spinz,Deo,50000.0,5,END CAP,10000.000000
37541,2019-12-01,Metro C&C_53,Spinz,Men Deo,50000.0,3,SHELF VISIBILITY,16666.666667
39423,2020-01-01,ABRL_Super_Bangalore,Spinz,Men Deo,285000.0,4,SIDE CAP,71250.000000
39482,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,47700.0,4,SIDE CAP,11925.000000

In [85]:
m2.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External,Element Type_x,Promotion1,Gross Price,Element Type
56924,2019-08-01,Spencers_D177,Spinz,DEO,Enchante,360,2,1,SPINZ WOMEN DEO ENCHANTE 150ml CAN,NaN,NaN,NaN,NaN

In [86]:
m22.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Gross Price,Item_Description_External,Element Type,Promotion2
27603,2019-08-01,Spar_30007,Spinz,Men Deo,70750.0,3,FSU,23583.333333

In [87]:
of_tp.shape, m2.shape

((86977, 11), (86977, 13))

In [88]:
of_tp = pd.merge(left=m2, right=m22, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal'],
        right_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal'], suffixes=('_x2', '_y2'))

In [89]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Gross Price_x2,Element Type_x2,Gross Price_y2,Item_Description_External_y2,Element Type_y2,Promotion2
8899,2019-02-01,Spencers_D176,Nyle,Shampoo,Pollution Shield,182,1,1,NYLE POLLUTION SHIELD SHMP 400ml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
of_tp[~of_tp['Element Type_y2'].isna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Gross Price_x2,Element Type_x2,Gross Price_y2,Item_Description_External_y2,Element Type_y2,Promotion2
20960,2019-04-01,Metro C&C_10,Spinz,Talc,Cool,2836,59,1,SPINZ COOL TALC 100G,NaN,NaN,50000.0,END CAP,50000.0,4.0,END CAP,12500.0
20961,2019-04-01,Metro C&C_10,Spinz,Talc,Enchante,6328,125,1,SPINZ TALC ENCHANTE 100GM,NaN,NaN,50000.0,END CAP,50000.0,4.0,END CAP,12500.0
20962,2019-04-01,Metro C&C_10,Spinz,Talc,Exotic,6387,118,2,SPINZ TALC EXOTIC 100GM,NaN,NaN,50000.0,END CAP,50000.0,4.0,END CAP,12500.0
20963,2019-04-01,Metro C&C_10,Spinz,Talc,Sandal,3252,63,1,SPINZ SANDAL TALC 90G,NaN,NaN,50000.0,END CAP,50000.0,4.0,END CAP,12500.0
20995,2019-04-01,Metro C&C_11,Spinz,Talc,Cool,6442,132,1,SPINZ COOL TALC 100G,NaN,NaN,50000.0,END CAP,50000.0,4.0,END CAP,12500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82568,2020-01-01,ABRL_Super_Bangalore,Spinz,Men Deo,Risk Taker,14697,147,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,285000.0,SIDE CAP,285000.0,4.0,SIDE CAP,71250.0
82698,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Flyer,10994,105,1,Spinz High Flyer 48Hrs. Deo 150 ml Can,NaN,NaN,47700.0,SIDE CAP,47700.0,4.0,SIDE CAP,11925.0
82699,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Hi Rider,12488,124,1,Spinz High Rider 48Hrs. Deo 150 ml Can,NaN,NaN,47700.0,SIDE CAP,47700.0,4.0,SIDE CAP,11925.0
82700,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Master Mover,15291,151,1,Spinz Master Mover 48Hrs. Deo 150 ml Can,NaN,NaN,47700.0,SIDE CAP,47700.0,4.0,SIDE CAP,11925.0
82701,2020-01-01,ABRL_Super_Hyderabad,Spinz,Men Deo,Risk Taker,15694,157,1,Spinz Risk Taker 48Hrs. Deo 150 ml Can,NaN,NaN,47700.0,SIDE CAP,47700.0,4.0,SIDE CAP,11925.0

In [91]:
of_tp.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal', 'Item_Description_External_x2',
       'Element Type_x', 'Promotion1', 'Gross Price_x2', 'Element Type_x2',
       'Gross Price_y2', 'Item_Description_External_y2', 'Element Type_y2',
       'Promotion2'],
      dtype='object')

In [92]:
of_tp[~of_tp['Element Type_x'].isna()].sample().transpose()

                                                           30763
Date                                         2019-05-01 00:00:00
Chain_Store_Code                       Reliance Retail_Jharkhand
Brand                                                      Spinz
Category Internal                                        Men Deo
Variant_x                                               Hi Flyer
Offtake Sales Value                                         5836
Offtake Sales Qty                                             43
Item Master.Item Description Internal                          1
Item_Description_External_x2           SPINZ DEO HI FLYER 150 ML
Element Type_x                                          SIDE CAP
Promotion1                                                 10325
Gross Price_x2                                               NaN
Element Type_x2                                              NaN
Gross Price_y2                                               NaN
Item_Description_External_y2                                 NaN
Element Type_y2                                              NaN
Promotion2                                                   NaN

In [94]:
of_tp = of_tp.iloc[:, [0,1,2,3,4,
                       5,6,
                       7,8,
                       9,10,  12,
                       -1]]

In [95]:
of_tp

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,3405,30,2,Chik Egg White Protein Shampoo180 ml Bottle,NaN,NaN,NaN,NaN
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,559,12,1,Fairever Fairness Cream 25 Gm,NaN,NaN,NaN,NaN
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,5254,29,3,IndicaBeard and Moustache Natural Black 32 gm Box,NaN,NaN,NaN,NaN
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,7975,210,3,Indica Easy Hair Color Natural Black25 ml Pouch,NaN,NaN,NaN,NaN
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,370,5,1,Karthika Shampoo Dryness Shield 175 Ml Bottle,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,0,0,1,INDICA HAIR COLOR NATURAL BLACK 40 ml,NaN,NaN,NaN,NaN
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,232,2,1,INDICA HAIR COLOUR NAT BLK 8UX5g,NaN,NaN,NaN,NaN
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,841,31,1,INDICA HAIR COLOR NATURAL BLACK 25 ml,NaN,NaN,NaN,NaN
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,0,0,1,KARTHIKA SHAMPOO 20U X 6ml,NaN,NaN,NaN,NaN
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,329949,11919,1,MEERA SHAMPOO STRNGHLTHY 20 U X 6 ml,NaN,NaN,NaN,NaN

In [96]:
of_tp['Promotion2'].sum()

13450160.0

In [97]:
tp2['Gross Price'].sum()

14990360.0

Make m3 from of_tp

In [98]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2
81701,2019-12-01,Walmart_4744,Nyle,Lotion,Carrot,2133,19,1,NYLE BODY LOTION CARROT400 ml,NaN,NaN,NaN,NaN

In [99]:
tp3.sample()

,Month,Proper Chain Name,Store Code,Brand,Category,Variant,Gross Price,Element Type
360,2019-08-01,Reliance C&C,Reliance C&C_3289,Indica,Hair Colour,Easy,20000.0,END CAP

In [100]:
m3 = pd.merge(left=of_tp, right=tp3, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x'],
        right_on=['Month', 'Store Code', 'Brand', 'Category', 'Variant'])

In [101]:
m3[~m3['Category'].isna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2,Month,Proper Chain Name,Store Code,Category,Variant,Gross Price,Element Type
21198,2019-04-01,Metro C&C_20,Indica,Hair Colour,Easy,14901,215,2,INDICA EASY BLACK -MINI PK6,NaN,NaN,NaN,NaN,2019-04-01,Metro C&C,Metro C&C_20,Hair Colour,Easy,50000.0,END CAP
22039,2019-04-01,Reliance Retail_Gujarat,Indica,Hair Colour,Easy,2025,43,1,INDICA EASY HIRCOLR 2 NTURL BLK 65 g CBD,NaN,NaN,NaN,NaN,2019-04-01,Reliance Retail,Reliance Retail_Gujarat,Hair Colour,Easy,15000.0,PARASITE
22109,2019-04-01,Reliance Retail_Maharashtra,Indica,Hair Colour,Easy,23745,586,3,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,2019-04-01,Reliance Retail,Reliance Retail_Maharashtra,Hair Colour,Easy,15000.0,PARASITE
22180,2019-04-01,Reliance Retail_Tamil Nadu,Indica,Hair Colour,Easy,26547,663,2,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,2019-04-01,Reliance Retail,Reliance Retail_Tamil Nadu,Hair Colour,Easy,15000.0,PARASITE
29473,2019-05-01,Metro C&C_12,Meera,Shampoo,AD,119619,1712,2,MEERA ANTI DANDRUFF SHMP 180ML,NaN,NaN,NaN,NaN,2019-05-01,Metro C&C,Metro C&C_12,Shampoo,AD,100000.0,END CAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,4993,48,2,Indica Creme Hair Colour Natural Black 1,NaN,NaN,NaN,NaN,2020-01-01,ABRL,ABRL_Super_Vizag,Hair Colour,Creme,52371.0,SIDE CAP
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,136383,4323,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,2020-01-01,Walmart,Walmart_4721,Shampoo,AD,50000.0,END CAP
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,91783,2250,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,2020-01-01,Walmart,Walmart_4725,Shampoo,AD,50000.0,END CAP
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,244338,7592,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,2020-01-01,Walmart,Walmart_4742,Shampoo,AD,50000.0,END CAP
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,84179,1925,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,2020-01-01,Walmart,Walmart_4799,Shampoo,AD,50000.0,END CAP

In [102]:
m3.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2,Month,Proper Chain Name,Store Code,Category,Variant,Gross Price,Element Type
34163,2019-05-01,Tesco_T001,Spinz,Deo,Trailblazer,530,3,1,Spinz Trail Blazer Gs Deo 150ml,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
m3.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal', 'Item_Description_External_x2',
       'Element Type_x', 'Promotion1', 'Element Type_x2', 'Promotion2',
       'Month', 'Proper Chain Name', 'Store Code', 'Category', 'Variant',
       'Gross Price', 'Element Type'],
      dtype='object')

In [104]:
m3 = m3[['Date', 'Chain_Store_Code', 'Brand',
          'Category Internal', 'Variant_x', 
          'Offtake Sales Value','Offtake Sales Qty',
         'Item Master.Item Description Internal','Item_Description_External_x2',
         'Element Type_x','Promotion1', 
         'Element Type_x2','Promotion2',
          'Gross Price', 'Element Type']]

In [105]:
m3[m3['Gross Price'].notna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price,Element Type
21198,2019-04-01,Metro C&C_20,Indica,Hair Colour,Easy,14901,215,2,INDICA EASY BLACK -MINI PK6,NaN,NaN,NaN,NaN,50000.0,END CAP
22039,2019-04-01,Reliance Retail_Gujarat,Indica,Hair Colour,Easy,2025,43,1,INDICA EASY HIRCOLR 2 NTURL BLK 65 g CBD,NaN,NaN,NaN,NaN,15000.0,PARASITE
22109,2019-04-01,Reliance Retail_Maharashtra,Indica,Hair Colour,Easy,23745,586,3,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,15000.0,PARASITE
22180,2019-04-01,Reliance Retail_Tamil Nadu,Indica,Hair Colour,Easy,26547,663,2,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,15000.0,PARASITE
29473,2019-05-01,Metro C&C_12,Meera,Shampoo,AD,119619,1712,2,MEERA ANTI DANDRUFF SHMP 180ML,NaN,NaN,NaN,NaN,100000.0,END CAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,4993,48,2,Indica Creme Hair Colour Natural Black 1,NaN,NaN,NaN,NaN,52371.0,SIDE CAP
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,136383,4323,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,91783,2250,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,244338,7592,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,84179,1925,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP

In [106]:
m32 = m3.groupby(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x']).aggregate({
    'Gross Price': lambda s: s.mean(), 
                                                'Item_Description_External_x2':lambda s: s.count(),
                                                'Element Type': lambda s: s.unique()}).reset_index()

In [107]:
m32

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Gross Price,Item_Description_External_x2,Element Type
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,NaN,1,NaN
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,NaN,1,NaN
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,NaN,1,NaN
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,NaN,1,NaN
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,NaN,1,NaN
...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,NaN,1,NaN
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,NaN,1,NaN
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,NaN,1,NaN
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,NaN,1,NaN
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,NaN,1,NaN

In [108]:
m32['Promotion3'] = m32.loc[:,'Gross Price']/m32.loc[:,'Item_Description_External_x2']

In [109]:
m32 = m32[~m32['Gross Price'].isna()]

In [110]:
m32

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Gross Price,Item_Description_External_x2,Element Type,Promotion3
21198,2019-04-01,Metro C&C_20,Indica,Hair Colour,Easy,50000.0,1,END CAP,50000.0
22039,2019-04-01,Reliance Retail_Gujarat,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
22109,2019-04-01,Reliance Retail_Maharashtra,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
22180,2019-04-01,Reliance Retail_Tamil Nadu,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
29473,2019-05-01,Metro C&C_12,Meera,Shampoo,AD,100000.0,1,END CAP,100000.0
...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,52371.0,1,SIDE CAP,52371.0
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0

In [111]:
m3.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price,Element Type
70299,2019-10-01,Spencers_S083,Spinz,Deo,Exotic,95,1,1,SPINZ WOMEN DEO EXOCTIC 150ml CAN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
m32.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Gross Price,Item_Description_External_x2,Element Type,Promotion3
50144,2019-07-01,Spencers_S038,Meera,Shampoo,AD,30000.0,1,END CAP,30000.0

In [113]:
m32

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Gross Price,Item_Description_External_x2,Element Type,Promotion3
21198,2019-04-01,Metro C&C_20,Indica,Hair Colour,Easy,50000.0,1,END CAP,50000.0
22039,2019-04-01,Reliance Retail_Gujarat,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
22109,2019-04-01,Reliance Retail_Maharashtra,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
22180,2019-04-01,Reliance Retail_Tamil Nadu,Indica,Hair Colour,Easy,15000.0,1,PARASITE,15000.0
29473,2019-05-01,Metro C&C_12,Meera,Shampoo,AD,100000.0,1,END CAP,100000.0
...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,52371.0,1,SIDE CAP,52371.0
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,50000.0,1,END CAP,50000.0

In [114]:
of_tp.shape, m3.shape

((86977, 13), (86977, 15))

In [115]:
of_tp = pd.merge(left=m3, right=m32, how='left',
        left_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x'],
        right_on=['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x'], suffixes=('_x3', '_y3'))

In [116]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2_x3,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price_x3,Element Type_x3,Gross Price_y3,Item_Description_External_x2_y3,Element Type_y3,Promotion3
82248,2020-01-01,ABRL_Hyper_Moments,CHIK,Shampoo,Egg,1251,16,1,ChikShampoo Hair Fall Prevent Egg White 340 ml...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
of_tp[~of_tp['Element Type_y3'].isna()]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2_x3,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price_x3,Element Type_x3,Gross Price_y3,Item_Description_External_x2_y3,Element Type_y3,Promotion3
21198,2019-04-01,Metro C&C_20,Indica,Hair Colour,Easy,14901,215,2,INDICA EASY BLACK -MINI PK6,NaN,NaN,NaN,NaN,50000.0,END CAP,50000.0,1.0,END CAP,50000.0
22039,2019-04-01,Reliance Retail_Gujarat,Indica,Hair Colour,Easy,2025,43,1,INDICA EASY HIRCOLR 2 NTURL BLK 65 g CBD,NaN,NaN,NaN,NaN,15000.0,PARASITE,15000.0,1.0,PARASITE,15000.0
22109,2019-04-01,Reliance Retail_Maharashtra,Indica,Hair Colour,Easy,23745,586,3,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,15000.0,PARASITE,15000.0,1.0,PARASITE,15000.0
22180,2019-04-01,Reliance Retail_Tamil Nadu,Indica,Hair Colour,Easy,26547,663,2,INDICA EASY HAIR CLR NATURL BLK 25 ml PP,NaN,NaN,NaN,NaN,15000.0,PARASITE,15000.0,1.0,PARASITE,15000.0
29473,2019-05-01,Metro C&C_12,Meera,Shampoo,AD,119619,1712,2,MEERA ANTI DANDRUFF SHMP 180ML,NaN,NaN,NaN,NaN,100000.0,END CAP,100000.0,1.0,END CAP,100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,4993,48,2,Indica Creme Hair Colour Natural Black 1,NaN,NaN,NaN,NaN,52371.0,SIDE CAP,52371.0,1.0,SIDE CAP,52371.0
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,136383,4323,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP,50000.0,1.0,END CAP,50000.0
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,91783,2250,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP,50000.0,1.0,END CAP,50000.0
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,244338,7592,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP,50000.0,1.0,END CAP,50000.0
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,84179,1925,3,MEERA ANTI DANDRUFF SHAMPOO 180 ml,NaN,NaN,NaN,NaN,50000.0,END CAP,50000.0,1.0,END CAP,50000.0

In [118]:
of_tp.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal',
       'Item_Description_External_x2_x3', 'Element Type_x', 'Promotion1',
       'Element Type_x2', 'Promotion2', 'Gross Price_x3', 'Element Type_x3',
       'Gross Price_y3', 'Item_Description_External_x2_y3', 'Element Type_y3',
       'Promotion3'],
      dtype='object')

In [119]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2_x3,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price_x3,Element Type_x3,Gross Price_y3,Item_Description_External_x2_y3,Element Type_y3,Promotion3
3239,2019-01-01,Spencers_H035,Spinz,Deo,Trailblazer,325,2,1,SPINZ TRAIL BLAZER DEO 150ml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
of_tp['Promotion3'].sum()

19215280.95238095

In [121]:
tp3['Gross Price'].sum()

24050919.0

In [122]:
tp['Gross Price'].sum()

39474929.0

of_tp.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,,16,17,-1]]

of_tp[(of_tp['Gross Price_x']>0) & (of_tp['Gross Price_x2']>0)]

In [123]:
p = of_tp[['Promotion1', 'Promotion2', 'Promotion3']].apply(lambda s: s.sum(), axis=1)

In [124]:
p.sum()

33099090.95238095

In [125]:
del p

drop the columns from of_tp

In [126]:
of_tp.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal',
       'Item_Description_External_x2_x3', 'Element Type_x', 'Promotion1',
       'Element Type_x2', 'Promotion2', 'Gross Price_x3', 'Element Type_x3',
       'Gross Price_y3', 'Item_Description_External_x2_y3', 'Element Type_y3',
       'Promotion3'],
      dtype='object')

In [127]:
of_tp.sample()

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Offtake Sales Value,Offtake Sales Qty,Item Master.Item Description Internal,Item_Description_External_x2_x3,Element Type_x,Promotion1,Element Type_x2,Promotion2,Gross Price_x3,Element Type_x3,Gross Price_y3,Item_Description_External_x2_y3,Element Type_y3,Promotion3
31306,2019-05-01,Spar_20015,Meera,Hair Oil,Herbal,131,2,1,MEERA HERBAL HAIR OIL 175ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
of_tp['Element Type'] = of_tp[['Element Type_x', 'Element Type_x2', 'Element Type_x3']].apply(lambda s: "_".join(s.dropna()), axis=1)

In [129]:
of_tp['Promotion'] = of_tp[['Promotion1', 'Promotion2', 'Promotion3']].apply(lambda s: s.sum(), axis=1)

In [130]:
of_tp.columns

Index(['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
       'Offtake Sales Value', 'Offtake Sales Qty',
       'Item Master.Item Description Internal',
       'Item_Description_External_x2_x3', 'Element Type_x', 'Promotion1',
       'Element Type_x2', 'Promotion2', 'Gross Price_x3', 'Element Type_x3',
       'Gross Price_y3', 'Item_Description_External_x2_y3', 'Element Type_y3',
       'Promotion3', 'Element Type', 'Promotion'],
      dtype='object')

In [131]:
of_tp2 = of_tp[['Date', 'Chain_Store_Code', 'Brand', 'Category Internal', 'Variant_x',
      'Item Master.Item Description Internal','Offtake Sales Value', 'Offtake Sales Qty',
      'Element Type', 'Promotion']]

In [132]:
of_tp2[of_tp2['Promotion']!=0.0]

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Item Master.Item Description Internal,Offtake Sales Value,Offtake Sales Qty,Element Type,Promotion
20960,2019-04-01,Metro C&C_10,Spinz,Talc,Cool,1,2836,59,END CAP,12500.0
20961,2019-04-01,Metro C&C_10,Spinz,Talc,Enchante,1,6328,125,END CAP,12500.0
20962,2019-04-01,Metro C&C_10,Spinz,Talc,Exotic,2,6387,118,END CAP,12500.0
20963,2019-04-01,Metro C&C_10,Spinz,Talc,Sandal,1,3252,63,END CAP,12500.0
20995,2019-04-01,Metro C&C_11,Spinz,Talc,Cool,1,6442,132,END CAP,12500.0
...,...,...,...,...,...,...,...,...,...,...
82831,2020-01-01,ABRL_Super_Vizag,Indica,Hair Colour,Creme,2,4993,48,SIDE CAP,52371.0
86584,2020-01-01,Walmart_4721,Meera,Shampoo,AD,3,136383,4323,END CAP,50000.0
86641,2020-01-01,Walmart_4725,Meera,Shampoo,AD,3,91783,2250,END CAP,50000.0
86728,2020-01-01,Walmart_4742,Meera,Shampoo,AD,3,244338,7592,END CAP,50000.0
86815,2020-01-01,Walmart_4799,Meera,Shampoo,AD,3,84179,1925,END CAP,50000.0

In [133]:
tp['Gross Price'].sum(), of_tp2['Promotion'].sum()

(39474929.0, 33099090.95238095)

In [134]:
of_tp2.shape

(86977, 10)

In [135]:
of_tp2

,Date,Chain_Store_Code,Brand,Category Internal,Variant_x,Item Master.Item Description Internal,Offtake Sales Value,Offtake Sales Qty,Element Type,Promotion
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,2,3405,30,,0.0
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,1,559,12,,0.0
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,3,5254,29,,0.0
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,3,7975,210,,0.0
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,1,370,5,,0.0
...,...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,1,0,0,,0.0
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,1,232,2,,0.0
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,1,841,31,,0.0
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,1,0,0,,0.0
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,1,329949,11919,,0.0

In [142]:
of_tp2.rename(columns={
    "Variant_x": 'Variant', 
    'Item Master.Item Description Internal':'Unique Items'
}, inplace=True)

In [143]:
of_tp2

,Date,Chain_Store_Code,Brand,Category Internal,Variant,Unique Items,Offtake Sales Value,Offtake Sales Qty,Element Type,Promotion
0,2019-01-01,ABRL_Hyper_Banjarahills,CHIK,Shampoo,Egg,2,3405,30,,0.0
1,2019-01-01,ABRL_Hyper_Banjarahills,FAIREVER,Fairness Cream,Regular,1,559,12,,0.0
2,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,B&M,3,5254,29,,0.0
3,2019-01-01,ABRL_Hyper_Banjarahills,Indica,Hair Colour,Easy,3,7975,210,,0.0
4,2019-01-01,ABRL_Hyper_Banjarahills,Karthika,Shampoo,Dryness Shield,1,370,5,,0.0
...,...,...,...,...,...,...,...,...,...,...
86972,2020-01-01,Walmart_4824,Indica,Hair Colour,Creme,1,0,0,,0.0
86973,2020-01-01,Walmart_4824,Indica,Hair Colour,Dye,1,232,2,,0.0
86974,2020-01-01,Walmart_4824,Indica,Hair Colour,Easy,1,841,31,,0.0
86975,2020-01-01,Walmart_4824,Karthika,Shampoo,Damage Shield,1,0,0,,0.0
86976,2020-01-01,Walmart_4824,Meera,Shampoo,Strong & Healthy,1,329949,11919,,0.0

In [144]:
#

In [145]:
#

In [146]:
of_tp2.to_excel('Offtake_TP.xlsx', index=False)